"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dj_database_url # <--- ADD THIS LINE at the top
from pickle import FALSE
from telnetlib import AUTHENTICATION

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = '-#x%uhqy(uom@f^ym_=(6$4ml!)mv$+&8_@3yi519ri966ac+f'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')


# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# ----------------- CHANGE THIS -----------------
# Control DEBUG mode with an environment variable
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'


#ALLOWED_HOSTS = ["*"]   
ALLOWED_HOSTS = [os.environ.get('VERCEL_URL'), '.vercel.app'] 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # new!
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django.contrib.sites",

    #Third Party
    'crispy_forms',
    "allauth",
    "allauth.account",

    #'taggit',

    "blog.apps.BlogConfig",
    "accounts.apps.AccountsConfig",
    "menu.apps.MenuConfig",
    "archive.apps.ArchiveConfig"
]

#django-crispy_forms
CRISPY_TEMPLATE_PACK="bootstrap4"

###########django-allauth config###############################
        #account logout Redirect
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT = 'home'

        #authentication Backend
SITE_ID=1
AUTHENTICATION_BACKENDS=(
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)
        #email backend service
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
#DEFAULT_FROM_EMAIl="admin@greenfield.com"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "greenfieldstudio@gmail.com"
EMAIL_HOST_PASSWORD = "ilovepainting"

ACCOUNT_SESSION_REMEMBER= False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE= False


    #emial only login
ACCOUNT_USERNAME_REQUIRED=False
ACCOUNT_AUTHENTICATION_METHOD="email"
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_UNIQUE_EMAIL=True




# When we get to tagging
#TAGGIT_CASE_INSENSITIVE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # new!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # new
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Replace your SQLite database configuration
DATABASES = {
    'default': dj_database_url.config(
        # Fallback to a local SQLite database for development if DATABASE_URL is not set
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, '/static/')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# greenfield_art/settings.py

import os
import dj_database_url # <--- ADD THIS LINE at the top

# ... keep existing imports ...

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# ----------------- CHANGE THIS -----------------
# Replace your hardcoded SECRET_KEY
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# ----------------- CHANGE THIS -----------------
# Control DEBUG mode with an environment variable
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ----------------- CHANGE THIS -----------------
# Configure ALLOWED_HOSTS for Vercel
ALLOWED_HOSTS = [os.environ.get('VERCEL_URL', '.vercel.app')]
# Add your custom domain here if you have one, e.g., 'www.yourdomain.com'


# Application definition
# ... (no changes needed here) ...

# ----------------- CHANGE THIS -----------------
# Replace your SQLite database configuration
DATABASES = {
    'default': dj_database_url.config(
        # Fallback to a local SQLite database for development if DATABASE_URL is not set
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# ... (no changes needed for templates, etc.) ...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

# This is where your static files are currently located, which is correct.
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# ----------------- ADD THIS -----------------
# This is where collectstatic will gather all static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"  # new




